name: New Action 1
description: custom pipeline action 0
inputs:
  WHO_TO_GREET:
    required: false
    default: ''
outputs:
  time:
    required: false
    default: ''
runs:
  using: node12
  main: action.js
