name: pipeline
'on': push
jobs:
  ui-tests-playwright:
    name: UI Tests (playwright)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project files
        uses: actions/checkout@v2
      - name: Setup nodejs and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo '::set-output name=dir::$(npm config get cache)'
      - name: Check cache directory
        uses: actions/cache@v2
        id: npm-cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies and run tests
        run: npm install && npm install --save-dev playwright
      - name: Run tests
        run: npx playwright tests/ui --headed --browser=all
      - name: Save artifacts (videos, screenshots, ...)
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: test-results/
      - name: Custom Action
        uses: .github/actions/action-0.yml
        id: action-0
        with:
          input_name: ${{ secrets.[input_name] }}
      - name: Results - Custom Action
        run: |
          echo 'input_name => ${{ steps['action-0']['outputs']['input_name']}}
      - name: Custom Action
        uses: .github/actions/action-1.yml
        id: action-1
        with:
          input_name: ${{ secrets.[input_name] }}
      - name: Results - Custom Action
        run: |
          echo 'input_name => ${{ steps['action-1']['outputs']['input_name']}}
  deployment-netlify:
    name: Deployment (Netlify)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project files
        uses: actions/checkout@v2
      - name: Setup nodejs and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo '::set-output name=dir::$(npm config get cache)'
      - name: Check cache directory
        uses: actions/cache@v2
        id: npm-cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install && npm install --save-dev netlify-cli
      - name: Build project files
        run: npm run build
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npx netlify deploy --prod --dir dist --auth $NETLIFY_AUTH_TOKEN
      - name: Get deployment URL
        id: deployment-url
        run: 'echo ''{ "url": "$(echo $DEPLOY_URL)" }'' > deployment-info.json'
      - name: Save deployment info
        uses: actions/upload-artifact@v2
        with:
          name: deployment-info
          path: ./deployment-info.json
